# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a2108f4ef1916eaf6475e2505f923d7fa39a24bb55de02de75ecabe30e883c5414bd84398fa64e8e2f604cb3001fefec914d03088ef015d17a35b8de2c3e27

test:
  secret_key_base: de7826dd12d79f56b334205e6a5376c04b5fbaa9231a09258986516e9589b3eee6c5253d49fc73c5078e81b22aec9982fe22ead34ae6a92019d1d3c369ace046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
